spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_sample
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
